### ISSUE TITLE
can't run nextjs example

### ISSUE THREAD

**Issue by KarthickSelvam** [serverless-stack/serverless-stack#1000]
Getting below error:
_Building Next.js site frontend

Error: There was a problem building the "Site" NextjsSite.
    at NextjsSite.buildApp (/Users/**/node_modules/@serverless-stack/resources/src/NextjsSite.ts:588:13)
    at new NextjsSite (/Users/**/node_modules/@serverless-stack/resources/src/NextjsSite.ts:146:16)
    at new MyStack (/Users/**/lib/MyStack.js:16:18)_

System OS: Mac

**Comment by fwang** [comment]
Hey @KarthickSelvam, did you npm/yarn install in the `frontend/` folder?

**Comment by KarthickSelvam** [comment]
yes that help thank!
