### ISSUE TITLE
IAM errors when deploying Datadog

### ISSUE THREAD

**Issue by paambaati** [serverless-stack/serverless-stack#1066]
When trying to add [Datadog](https://docs.serverless-stack.com/monitoring-your-app-in-prod#datadog) to my serverless stack, I run into an IAM error.

```
Using stage: sst-gp
Preparing your SST app
Detected tsconfig.json
Transpiling source
Linting source
Running type checker

=======================
 Deploying debug stack
=======================

Deploying stacks
Checking deploy status...
sst-gp-appsync-debug-stack | UPDATE_IN_PROGRESS | AWS::CloudFormation::Stack | sst-gp-appsync-debug-stack
sst-gp-appsync-debug-stack | DELETE_COMPLETE | AWS::IAM::Role | LogRetentionXXXXX
Checking deploy status...
Checking deploy status...
Checking deploy status...
sst-gp-appsync-debug-stack | UPDATE_FAILED | AWS::Lambda::Function | Resource AccessDenied. User doesn't have permission to call iam:GetRole
sst-gp-appsync-debug-stack | CREATE_IN_PROGRESS | AWS::IAM::Role | LogRetentionXXXXX
sst-gp-appsync-debug-stack | UPDATE_FAILED | AWS::Lambda::Function | CustomS3AutoDeleteObjectsCustomResourceProviderHandlerXXXXX
sst-gp-appsync-debug-stack | UPDATE_FAILED | AWS::Lambda::Function | ConnectXXXXX
sst-gp-appsync-debug-stack | UPDATE_FAILED | AWS::Lambda::Function | DisconnectXXXXX
sst-gp-appsync-debug-stack | CREATE_IN_PROGRESS | AWS::IAM::Role | LogRetentionXXXXX
sst-gp-appsync-debug-stack | CREATE_FAILED | AWS::IAM::Role | LogRetentionXXXXX
sst-gp-appsync-debug-stack | UPDATE_FAILED | AWS::CloudFormation::Stack | sst-gp-appsync-debug-stack

 ❌  sst-gp-appsync-debug-stack failed: AccessDenied. User doesn't have permission to call iam:GetRole


Stack sst-gp-appsync-debug-stack
  Status: failed
  Error: AccessDenied. User doesn't have permission to call iam:GetRole

Failed to deploy debug stack sst-gp-appsync-debug-stack
```

<details>
<summary>Click to view output with `--verbose` flag</summary>

```
SST: 0.53.0
CDK: 1.132.0
Using stage: sst-gp
Preparing your SST app
Detected tsconfig.json
Transpiling source
Linting source
Running type checker

=======================
 Deploying debug stack
=======================

synth {
  output: 'cdk.out',
  app: 'node bin/index.js sst-gp-appsync-debug-stack sst-gp xx-xxxx-0 /Users/gp/Projects/appsync /Users/gp/Projects/appsync/.build/lib',
  rollback: false,
  roleArn: undefined,
  verbose: 2,
  noColor: false
}
CDK toolkit version: 1.132.0 (build 5c75891)
Command line arguments: {
  _: [ 'synth' ],
  'version-reporting': false,
  versionReporting: false,
  app: 'node bin/index.js sst-gp-appsync-debug-stack sst-gp xx-xxxx-0 /Users/gp/Projects/appsync /Users/gp/Projects/appsync/.build/lib',
  a: 'node bin/index.js sst-gp-appsync-debug-stack sst-gp xx-xxxx-0 /Users/gp/Projects/appsync /Users/gp/Projects/appsync/.build/lib',
  output: 'cdk.out',
  o: 'cdk.out',
  quiet: true,
  q: true,
  verbose: 1,
  v: 1,
  disableVersionCheck: 'true',
  lookups: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  debug: false,
  ec2creds: undefined,
  i: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  validation: true,
  '$0': '../../../../aws-cdk/bin/cdk'
}
cdk.json: {
  "app": "node bin/index.js",
  "context": {
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true"
  }
}
merged settings: {
  versionReporting: false,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'node bin/index.js sst-gp-appsync-debug-stack sst-gp xx-xxxx-0 /Users/gp/Projects/appsync /Users/gp/Projects/appsync/.build/lib',
  context: {
    '@aws-cdk/core:enableStackNameDuplicates': 'true',
    'aws-cdk:enableDiffNoFail': 'true'
  },
  debug: false,
  assetMetadata: true,
  toolkitBucket: {},
  staging: true,
  bundlingStacks: [ '*' ],
  lookups: true
}
Determining if we're on an EC2 instance.
Does not look like an EC2 instance.
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to xx-xxxx-0
Resolving default credentials
Retrieved account ID XXXXXXXXXX from disk cache
Setting "CDK_DEFAULT_ACCOUNT" environment variable to XXXXXXXXXX
context: {
  '@aws-cdk/core:enableStackNameDuplicates': 'true',
  'aws-cdk:enableDiffNoFail': 'true',
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
  'aws:cdk:disable-version-reporting': true,
  'aws:cdk:bundling-stacks': [ '*' ]
}
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: 'xx-xxxx-0',
  CDK_DEFAULT_ACCOUNT: 'XXXXXXXXXX',
  CDK_CONTEXT_JSON: '{"@aws-cdk/core:enableStackNameDuplicates":"true","aws-cdk:enableDiffNoFail":"true","aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true,"aws:cdk:disable-version-reporting":true,"aws:cdk:bundling-stacks":["*"]}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '14.0.0',
  CDK_CLI_VERSION: '1.132.0'
}
Deploying stacks
deploy stack: started sst-gp-appsync-debug-stack
deploy stack: get pre-deploy status
deploy stack: get pre-deploy status: {
  StackStatus: 'UPDATE_FAILED',
  LastUpdatedTime: 2021-11-19T05:09:15.739Z
}
deploy stack: check template changed
deploy stack: run cdk deploy
deploy stack: poll stack status
deploy stack: poll stack status: {
  StackStatus: 'UPDATE_FAILED',
  LastUpdatedTime: 2021-11-19T05:09:15.739Z
}
deploy stack: poll stack status: unknown
deploy stack: poll stack status: {
  StackStatus: 'UPDATE_FAILED',
  LastUpdatedTime: 2021-11-19T05:09:15.739Z
}
deploy stack: poll stack status: unknown
deploy stack: poll stack status: {
  StackStatus: 'UPDATE_FAILED',
  LastUpdatedTime: 2021-11-19T05:09:15.739Z
}
deploy stack: poll stack status: unknown
deploy stack: poll stack status: {
  StackStatus: 'UPDATE_FAILED',
  LastUpdatedTime: 2021-11-19T05:09:15.739Z
}
deploy stack: poll stack status: unknown
deploy stack: poll stack status: {
  StackStatus: 'UPDATE_FAILED',
  LastUpdatedTime: 2021-11-19T05:09:15.739Z
}
deploy stack: poll stack status: unknown
deploy stack: poll stack status: {
  StackStatus: 'UPDATE_FAILED',
  LastUpdatedTime: 2021-11-19T05:09:15.739Z
}
deploy stack: poll stack status: unknown
deploy stack: poll stack status: {
  StackStatus: 'UPDATE_FAILED',
  LastUpdatedTime: 2021-11-19T05:09:15.739Z
}
deploy stack: poll stack status: unknown
deploy stack: poll stack status: {
  StackStatus: 'UPDATE_FAILED',
  LastUpdatedTime: 2021-11-19T05:09:15.739Z
}
deploy stack: poll stack status: unknown
deploy stack: poll stack status: {
  StackStatus: 'UPDATE_FAILED',
  LastUpdatedTime: 2021-11-19T05:09:15.739Z
}
deploy stack: poll stack status: unknown
deploy stack: poll stack status: {
  StackStatus: 'UPDATE_FAILED',
  LastUpdatedTime: 2021-11-19T05:09:15.739Z
}
deploy stack: poll stack status: unknown
deploy stack: poll stack status: {
  StackStatus: 'UPDATE_IN_PROGRESS',
  LastUpdatedTime: 2021-11-19T05:21:43.761Z
}
deploy stack: poll stack status: cf update started
deploy stack: done sst-gp-appsync-debug-stack {
  status: 'deploying',
  statusReason: undefined,
  account: 'XXXXXXXXXX',
  outputs: {
    BucketArn: 'arn:aws:s3:::sst-gp-appsync-debug-stack-bucket83908e77-xxxxxxxx',
    BucketName: 'sst-gp-appsync-debug-stack-bucket83908e77-xxxxxxxx',
    Endpoint: 'wss://xxxxxxx.execute-api.xx-xxxx-0.amazonaws.com/sst-gp'
  },
  exports: {}
}
Checking deploy status...
deploy stack: run cdk deploy: exited with code null
Fetching stack events sst-gp-appsync-debug-stack
sst-gp-appsync-debug-stack | UPDATE_IN_PROGRESS | AWS::CloudFormation::Stack | sst-gp-appsync-debug-stack
sst-gp-appsync-debug-stack | DELETE_COMPLETE | AWS::IAM::Role | LogRetentionXXXXXXXX
Checking stack status sst-gp-appsync-debug-stack
Fetching stack events sst-gp-appsync-debug-stack
Checking stack status sst-gp-appsync-debug-stack
Checking deploy status...
Fetching stack events sst-gp-appsync-debug-stack
Checking stack status sst-gp-appsync-debug-stack
Checking deploy status...
Fetching stack events sst-gp-appsync-debug-stack
Checking stack status sst-gp-appsync-debug-stack
Checking deploy status...
Fetching stack events sst-gp-appsync-debug-stack
sst-gp-appsync-debug-stack | UPDATE_FAILED | AWS::Lambda::Function | CustomS3AutoDeleteObjectsCustomResourceProviderHandlerXXXXX AccessDenied. User doesn't have permission to call iam:GetRole
sst-gp-appsync-debug-stack | CREATE_IN_PROGRESS | AWS::IAM::Role | LogRetentionXXXXXXXX
sst-gp-appsync-debug-stack | UPDATE_FAILED | AWS::Lambda::Function | DisconnectXXXXXX
sst-gp-appsync-debug-stack | UPDATE_FAILED | AWS::Lambda::Function | Resource
sst-gp-appsync-debug-stack | UPDATE_FAILED | AWS::Lambda::Function | ConnectXXXXXX
sst-gp-appsync-debug-stack | CREATE_IN_PROGRESS | AWS::IAM::Role | LogRetentionXXXXXXXX
sst-gp-appsync-debug-stack | CREATE_FAILED | AWS::IAM::Role | LogRetentionXXXXXXXX
Checking stack status sst-gp-appsync-debug-stack
Fetching stack events sst-gp-appsync-debug-stack
sst-gp-appsync-debug-stack | UPDATE_FAILED | AWS::CloudFormation::Stack | sst-gp-appsync-debug-stack
Checking stack status sst-gp-appsync-debug-stack
Error: Stack sst-gp-appsync-debug-stack failed to deploy: UPDATE_FAILED
    at getDeployStatus (/Users/gp/Projects/appsync/node_modules/@serverless-stack/core/dist/index.js:371:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/gp/Projects/appsync/node_modules/@serverless-stack/core/dist/index.js:316:58
    at async Promise.all (index 0)
    at updateDeployStatuses (/Users/gp/Projects/appsync/node_modules/@serverless-stack/core/dist/index.js:297:9)
    at Object.deployPoll (/Users/gp/Projects/appsync/node_modules/@serverless-stack/core/dist/index.js:488:5)
    at deploy (/Users/gp/Projects/appsync/node_modules/@serverless-stack/cli/scripts/util/cdkHelpers.js:463:22)
    at deployDebugStack (/Users/gp/Projects/appsync/node_modules/@serverless-stack/cli/scripts/start.js:245:21)
    at Object.module.exports [as start] (/Users/gp/Projects/appsync/node_modules/@serverless-stack/cli/scripts/start.js:107:29)

 ❌  sst-gp-appsync-debug-stack failed: AccessDenied. User doesn't have permission to call iam:GetRole


Stack sst-gp-appsync-debug-stack
  Status: failed
  Error: AccessDenied. User doesn't have permission to call iam:GetRole

deployRet [
  {
    name: 'sst-gp-appsync-debug-stack',
    status: 'failed',
    errorMessage: "AccessDenied. User doesn't have permission to call iam:GetRole",
    outputs: {},
    exports: {}
  }
]
Error: Failed to deploy debug stack sst-gp-appsync-debug-stack
    at deployDebugStack (/Users/gp/Projects/appsync/node_modules/@serverless-stack/cli/scripts/start.js:258:11)
    at Object.module.exports [as start] (/Users/gp/Projects/appsync/node_modules/@serverless-stack/cli/scripts/start.js:107:29)
Failed to deploy debug stack sst-gp-appsync-debug-stack

```

</details>

Here's what my `index.ts` looks like –

```typescript
import AppSyncStack from './AppSyncStack'
import * as sst from '@serverless-stack/resources'
import { Datadog } from 'datadog-cdk-constructs'

const DEFAULT_NODEJS_RUNTIME = 'nodejs14.x'
const { DATADOG_API_KEY } = process.env

export default function main(app: sst.App): void {
  app.setDefaultFunctionProps({
    runtime: DEFAULT_NODEJS_RUNTIME,
  })

  // Create main stack.
  const stack = new AppSyncStack(app, 'appsync-stack')

  // Attach Datadog to all Lambda functions in main stack.
  if (DATADOG_API_KEY) {
    const datadog = new Datadog(stack, 'Datadog', {
      nodeLayerVersion: 65,
      extensionLayerVersion: 13,
      apiKey: DATADOG_API_KEY,
    })

    datadog.addLambdaFunctions(stack.getAllFunctions())
  } else {
    console.warn('[WARN] Starting stack without Datadog!')
  }
}
```

Can you folks help understand what is happening here?

**Comment by paambaati** [comment]
Nevermind, recreating the stack fixed this.
