### ISSUE TITLE
Modules: "require is not defined in ES module scope"

### ISSUE THREAD

**Issue by revmischa** [serverless-stack/serverless-stack#1111]
I'm trying to port my CDK app to SST. I use ES Modules because I use `@aws-cdk/aws-lambda-nodejs` which uses `esbuild`, meaning tree-shaking only works in ESM projects. 

(Note that the [docs](https://docs.serverless-stack.com/faq#why-does-sst-not-use-cdks-built-in-way-to-build-nodejs-functions) that say SST uses its own Lambda builder so it can use `esbuild` is very strange since NodejsFunction already does and you can customize how it builds)

```
> sst deploy "--stage" "prod" "--region" "us-east-1"

Using stage: prod
Preparing your SST app
Detected tsconfig.json
Transpiling source
Linting source
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/cyber/dev/platform/packages/infra/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/cyber/dev/platform/packages/infra/.build/eslint.js:10:20
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
There was a problem linting the source.
```

`eslint.js` does in fact call `const { ESLint } = require("eslint");` which is not valid in ESM. Maybe use import or name the files with the `.cjs` extension?

If I disable linting then I run into the same problem in `run.js`.

**Comment by revmischa** [comment]
I think the easiest way to fix this is to write out a package.json file in `.build` with the sole contents:
`{"type": "commonjs"}`
This works for me if I do it manually. I was trying to see if there was somewhere in the code that would be a good place to add that simple writeFileSync call but I wasn't sure where exactly. I can make a PR if you point to me where.

It would be great to use ES modules though. Esbuild isn't really that great of a tool for lambda development if you use commonjs because it can't tree shake, resulting in larger bundles, and larger cold start times.
