### ISSUE TITLE
`sst start` needs to handle x-ray enabled aws-sdk better

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#123]
When x-ray is enabled for aws-sdk:
```
require('aws-xray-sdk').captureAWS(AWS);
```
When functions are triggered, request fails with the error below. Users would need to disable X-ray when running inside `sst start`. Ideally SST should gracefully handle this.
```
{
  name: 'Error',
  message: 'Failed to get the current sub/segment from the context.',
  stack: 'Error: Failed to get the current sub/segment from the context.\n' +
    '    at Object.contextMissingRuntimeError [as contextMissing] (/Users/frank/Sites/seed-api/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)\n' +
    '    at Object.getSegment (/Users/frank/Sites/seed-api/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)\n' +
    '    at Object.resolveSegment (/Users/frank/Sites/seed-api/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)\n' +
    '    at features.constructor.captureAWSRequest [as customRequestHandler] (/Users/frank/Sites/seed-api/node_modules/aws-xray-sdk-core/lib/patchers/aws_p.js:66:29)\n' +
    '    at features.constructor.addAllRequestListeners (/Users/frank/Sites/seed-api/node_modules/aws-sdk/lib/service.js:279:34)\n' +
    '    at features.constructor.makeRequest (/Users/frank/Sites/seed-api/node_modules/aws-sdk/lib/service.js:203:10)\n' +
    '    at features.constructor.svc.<computed> [as getItem] (/Users/frank/Sites/seed-api/node_modules/aws-sdk/lib/service.js:674:23)\n' +
    '    at DocumentClient.makeServiceRequest (/Users/frank/Sites/seed-api/node_modules/aws-sdk/lib/dynamodb/document_client.js:97:32)\n' +
    '    at DocumentClient.get (/Users/frank/Sites/seed-api/node_modules/aws-sdk/lib/dynamodb/document_client.js:263:17)\n' +
    '    at Function.<anonymous> (/Users/frank/Sites/seed-api/libs/aws-dynamodb-lib.js:144:27)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /Users/frank/Sites/seed-api/services/sst/.build/services/scripts/lambda.js:51:61\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __async (/Users/frank/Sites/seed-api/services/sst/.build/services/scripts/lambda.js:33:10)\n' +
    '    at Function.get (/Users/frank/Sites/seed-api/libs/aws-dynamodb-lib.js:140:26)\n' +
    '    at /Users/frank/Sites/seed-api/models/org.js:64:33\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /Users/frank/Sites/seed-api/services/sst/.build/services/scripts/lambda.js:51:61\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __async (/Users/frank/Sites/seed-api/services/sst/.build/services/scripts/lambda.js:33:10)\n' +
    '    at getByOi (/Users/frank/Sites/seed-api/models/org.js:63:38)\n' +
    '    at /Users/frank/Sites/seed-api/services/sst/services/scripts/lambda.js:10:24\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /Users/frank/Sites/seed-api/services/sst/.build/services/scripts/lambda.js:51:61\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __async (/Users/frank/Sites/seed-api/services/sst/.build/services/scripts/lambda.js:33:10)\n' +
    '    at handler (/Users/frank/Sites/seed-api/services/sst/services/scripts/lambda.js:8:33)\n' +
    '    at /Users/frank/Sites/seed-api/services/sst/node_modules/@serverless-stack/cli/assets/lambda-invoke/bootstrap.js:119:18'
}
```

**Comment by fwang** [comment]
Leaving a note here with Sam's X-ray mock:
```js
import AWSXRay, { Segment, Subsegment } from 'aws-xray-sdk';
const segmentStack: (Segment | Subsegment)[] = [];
function getDummySegment(name: string) {
  return {
    addNewSubsegment(name: string) {
      const indentation = '  '.repeat((segmentStack.length - 1) * 2);
      console.log('%s*** Begin: %s', indentation, name);
      return getDummySegment(name);
    },
    close() {
      const indentation = '  '.repeat((segmentStack.length - 1) * 2);
      console.log(
        '%s*** End: %s (%dms)',
        indentation,
        this.name,
        Date.now() - this.startTime
      );
    },
    name,
    startTime: Date.now(),
  };
}
export function startSegment(segmentName: string) {
  if (segmentStack.length === 0) {
    segmentStack.push(
      (process.env.IS_LOCAL
        ? getDummySegment('Base')
        : AWSXRay.getSegment()) as Segment
    );
  }
  segmentStack.push(segmentStack.slice(-1)[0].addNewSubsegment(segmentName));
}
export function endSegment() {
  const segment = segmentStack.pop();
  if (segment) {
    segment.close();
  }
}
```

Usage:
```js
startSegment('Do the thing');
doIt();
endSegment();
```

Slack link https://serverless-stack.slack.com/archives/C01JG3B20RY/p1641945781208300
