### ISSUE TITLE
Using the function's bundle.nodeModules property causes error

### ISSUE THREAD

**Issue by mlerner-ml** [serverless-stack/serverless-stack#1279]
Serverless Stack: 0.60.2
CDK: 2.7.0

When bundling a module with the `bundle.nodeModules` property:
```ts
export default function main(app: sst.App): void {
  // Set default runtime for all functions
  app.setDefaultFunctionProps({
    runtime: "nodejs14.x",
    memorySize: 128,
    bundle: {
      nodeModules: ['node-pg-format'],
    },
  });

  const MainStack = new MainStack(app, "main-stack");
}

```
I get the following error (this also occurs when adding `bundle.nodeModules` to the function itself):
```
Building function src/lambdas/lambda.main

SyntaxError: /Users/{{user}}/Documents/projects/{{repo}}/backend/.sst/artifacts/d8b22502/package.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.readFileSync (/Users/{{user}}/Documents/projects/{{repo}}/backend/node_modules/jsonfile/index.js:52:17)
    at installNodeModules (/Users/{{user}}/Documents/projects/{{repo}}/backend/node_modules/@serverless-stack/core/dist/runtime/handler/node.js:296:41)
    at Object.bundle (/Users/{{user}}/Documents/projects/{{repo}}/backend/node_modules/@serverless-stack/core/dist/runtime/handler/node.js:217:13)
    at Object.bundle (/Users/{{user}}/Documents/projects/{{repo}}/backend/node_modules/@serverless-stack/core/dist/runtime/handler/handler.js:19:16)
    at new Function (/Users/{{user}}/Documents/projects/{{repo}}/backend/node_modules/@serverless-stack/resources/src/Function.ts:361:39)
    at new MainStack (/Users/{{user}}/Documents/projects/{{repo}}/backend/stacks/MainStack.ts:106:42)
    at Object.main (/Users/{{user}}/Documents/projects/{{repo}}/backend/stacks/index.ts:23:34)
    at Object.<anonymous> (/Users/{{user}}/Documents/projects/{{repo}}/backend/.build/run.js:94:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
```

**Comment by fwang** [comment]
Hey @mlerner-ml, are you still having this issue?

If you could share the content of the `package.json` file in the issue, ie.
```bash
/Users/{{user}}/Documents/projects/{{repo}}/backend/.sst/artifacts/d8b22502/package.json
```

**Comment by thdxr** [comment]
If you update to the latest version this issue should be fixed
