### ISSUE TITLE
NextJS API Routes 503 due to @serverless-stack/nextjs-lambda

### ISSUE THREAD

**Issue by itsinprog** [serverless-stack/serverless-stack#1334]
After building and deploying my app the produced lambdas are missing critical webpack files causing the lambda to fail invocation and return 503 CloudFront error page.

    "@serverless-stack/cli": "0.60.11",
    "@serverless-stack/resources": "0.60.11",
    "next": "12.0.8",
 
        "Error: Cannot find module '../../webpack-api-runtime.js'",
        "Require stack:",
        "- /var/task/pages/api/hello.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:667:27)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at /var/task/pages/api/hello.js:173:27",
        "    at Object.<anonymous> (/var/task/pages/api/hello.js:179:3)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)"
 
When creating a build with `sst build`, you can see the files below for api-lambda 

<img width="258" alt="Screen Shot 2022-02-05 at 11 09 07 AM" src="https://user-images.githubusercontent.com/43507394/152651514-b1ecef23-2d17-4fdd-ae7a-97709c02b901.png">

When building with serverless for the serverless-next component, which works on deployment, it builds the same code with the needed the webpack runtime files.
<img width="295" alt="Screen Shot 2022-02-05 at 11 11 32 AM" src="https://user-images.githubusercontent.com/43507394/152651565-c0ea1259-eb6f-437f-9f10-5ae270a5bd5b.png">

The difference between the two builders is that serverless-next is using [@sls-next/lambda-at-edge](https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/libs/lambda-at-edge) which is building correctly, unlike @serverless-stack/nextjs-lambda.

**Comment by fwang** [comment]
Hi @itsinprog, thanks for bringing this up. Taking a look!

**Comment by rfoel** [comment]
I'm having trouble with that too, only when using `getServerSideProps`. 
Where did you find the stack trace? I'm having trouble locating myself in all the lambdas, log groups and buckets.

**Comment by fwang** [comment]
@itsinprog @rfoel I will try to have a fix by the end of the week for this. In the mean while, can you try downgrading to Next.js 11 and see if it works?

**Comment by rfoel** [comment]
@fwang I have an update. My problem wasn't with serverless-stack itself, but the way I was build my Next.js app. I was using Next.js v11 and using styled-components, so I had a next.config.js file and was using `babel-plugin-styled-components`. So basically I wasn't using swc to build my Next.js but babel, and apparently it was causing the build issues.

After updating to Next.js v12 and removing the extra config (because it has experimental support for styled-components with swc) it started working properly.

**Comment by rfoel** [comment]
@fwang Next.js 11 does work.

**Comment by fwang** [comment]
@rfoel @itsinprog This should be fixed in [v0.63.0](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.63.0).

Note that we made some changes to the `NextjsSite` in v0.63.0, the steps to update is in the [release note](https://github.com/serverless-stack/serverless-stack/releases/tag/v0.63.0). Should only take a min or two to make the change :)

**Comment by rfoel** [comment]
@fwang I think it's worth to note that `NextjsSite` only works with Next.js v11.

**Comment by fwang** [comment]
Hey @rfoel, v12 still doesn't work after updating to v0.63.0?

**Comment by scttcper** [comment]
V12 is working for me after the upgrade, or at least pages with SSR

**Comment by fwang** [comment]
@scttcper thanks for the update!

**Comment by rfoel** [comment]
@fwang I still get 503 on revalidation with SWR and API calls. SSR works though. You can check out [here](https://rfoel.dev/blog/como-subir-uma-aplicacao-next.js-na-aws-usando-serverless-stack) where I am using it, also the [source code](https://github.com/rfoel/rfoel.dev).
