### ISSUE TITLE
Undefined when manually loading Cognito

### ISSUE THREAD

**Issue by BlackFenix2** [serverless-stack/serverless-stack#1385]
When i try to add an AWS cognito userpool to my serverless stack, i get this error:
```sh

    "TypeError: Cannot read properties of undefined (reading 'UserPool')\n" +
    '    at new BipStack (C:\\Users\\Asus\\Documents\\GitHub\\bip\\aws-backend\\stacks\\BipStack.ts:23:34)\n' +
    '    at Object.main (C:\\Users\\Asus\\Documents\\GitHub\\bip\\aws-backend\\stacks\\index.ts:17:3)\n' +
    '    at Object.<anonymous> (C:\\Users\\Asus\\Documents\\GitHub\\bip\\aws-backend\\.build\\run.js:94:16)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:981:32)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n' +
    '    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n' +
    '    at node:internal/main/run_main_module:17:47\n' +
    '\n'
}
There was an error synthesizing your app.
```

**Comment by BlackFenix2** [comment]
closing, i was importing
