### ISSUE TITLE
v0.69.0 RuntimeHandlerNotFound: sst start cannot handle default exported functions (and sometimes named ones)

### ISSUE THREAD

**Issue by aaroneaton** [serverless-stack/serverless-stack#1577]
```
SST: 0.69.0
CDK: 2.15.0
```

I saw that this was once fixed in #1315 but it may have popped up again.

Original code:
```typescript
/* ... */
const server = new ApolloServer({
  typeDefs: schema,
  resolvers,
  cache,
  dataSources: () => ({
    user: new SalesforceUserDataSource(cachekeySeparator),
    userOrders: new SalesforceUserOrderDataSource(cachekeySeparator),
  }),
});

export const handler = server.createHandler();
```

Built code:
```javascript
var server = new import_apollo_server_lambda4.ApolloServer({
  typeDefs: schema,
  resolvers,
  cache,
  dataSources: () => ({
    user: new SalesforceUserDataSource(cachekeySeparator),
    userOrders: new SalesforceUserOrderDataSource(cachekeySeparator)
  })
});
var apiGateway_default = () => server.createHandler();
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {});

/* ... */

var apiGateway_exports = {};
__export(apiGateway_exports, {
  default: () => apiGateway_default
});
module.exports = __toCommonJS(apiGateway_exports)
```

Full error:
```
Unhandled Promise Rejection     {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Runtime.HandlerNotFound: /Users/aeaton/Projects/ama-infrastructure/.sst/artifacts/neuron-aaron-ama-infrastructure-ama-api-gateway-Api-Lambda_POST_-graphql/src/ApiGateway/apiGateway.handler is undefined or not exported","reason":"Runtime.HandlerNotFound: /Users/aeaton/Projects/ama-infrastructure/.sst/artifacts/neuron-aaron-ama-infrastructure-ama-api-gateway-Api-Lambda_POST_-graphql/src/ApiGateway/apiGateway.handler is undefined or not exported","promise":{},"stack":["Runtime.UnhandledPromiseRejection: Runtime.HandlerNotFound: /Users/aeaton/Projects/ama-infrastructure/.sst/artifacts/neuron-aaron-ama-infrastructure-ama-api-gateway-Api-Lambda_POST_-graphql/src/ApiGateway/apiGateway.handler is undefined or not exported","    at process.<anonymous> (file:///Users/aeaton/Projects/ama-infrastructure/node_modules/@serverless-stack/aws-lambda-ric/lib/index.js:34:23)","    at process.emit (events.js:400:28)","    at process.emit (domain.js:475:12)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
```

Any ideas about what could be happening?

**Comment by aaroneaton** [comment]
Not sure what was causing this, but building the project from scratch (delete node_modules, build folders, etc) seemed to fix it.

**Comment by fwang** [comment]
Oh I see. Let me know if this pops up again.
