### ISSUE TITLE
sst remove fails when path contains whitespace

### ISSUE THREAD

**Issue by borissuska** [serverless-stack/serverless-stack#1651]
### Error

```
➜  sst-app git:(main) ✗ npm run remove

> sst-app@0.1.0 remove /path/to/workspace/dir name/sst-app
> sst remove

Using stage: Administrator
Preparing your SST app
Removing debug stack
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/path/to/workspace/dir'
Require stack:
- /path/to/workspace/dir name/sst-app/node_modules/@serverless-stack/cli/assets/debug-stack/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/path/to/workspace/dir name/sst-app/node_modules/@serverless-stack/cli/assets/debug-stack/bin/index.js:17:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path/to/workspace/dir name/sst-app/node_modules/@serverless-stack/cli/assets/debug-stack/bin/index.js'
  ]
}

There was an error synthesizing your app.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sst@0.1.0 remove: `sst remove`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sst@0.1.0 remove script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2022-04-22T12_03_05_873Z-debug.log
```

### Steps to reproduce:

```
# create dir with whitespace
mkdir "dir name"
cd dir\ name

# init sst app in it
npx create-serverless-stack@latest sst-app
cd sst-app
npm run start # works perfectly

npm run remove # fails
```

### Workaround:

```
cd ../..
mv "dir name" dir_name
cd dir_name/sst-app
npm run remove
```

### OS:

macOS 12.3 (21E230)
Darwin 21.4.0

node v14.17.6
npm/npx 6.14.15

SST: 0.69.7
CDK: 2.15.0

**Comment by fwang** [comment]
Hey @borissuska, thanks for reporting this!

This should be fixed in a recent release. I can confirm it's fixed in v1.2.19.
