### ISSUE TITLE
Can't deploy new stack after manual cleanup

### ISSUE THREAD

**Issue by HundredPercentCoverage** [serverless-stack/serverless-stack#1676]
I've been playing with SST for a few days and I love it, although I wanted to remove all the stacks I had been playing with before I started getting charged. After running `npx sst remove` they seemed to be removed save for debug stack items like S3 buckets and roles, which I removed manually.

When I tried bootstrapping a stack again today, when I run `npx sst start` I get the following (after some redaction):

```
=======================
 Deploying debug stack 
=======================


Deploying stacks

✨  Synthesis time: 0.02s

hpc-test-sst-debug-stack: deploying...
current credentials could not be used to assume 'arn:aws:iam::[...]:role/cdk-[...]-deploy-role-[...]-eu-west-1', but are for the right account. Proceeding anyway.
[0%] start: Publishing bdb08b9984816ecf43301a0c6d8913e270ee2448940b6b95e430dd222a4d90be:[...]-eu-west-1
current credentials could not be used to assume 'arn:aws:iam::[...]:role/cdk-[...]-file-publishing-role-[...]-eu-west-1', but are for the right account. Proceeding anyway.
[25%] fail: No bucket named 'cdk-[...]-assets-[...]-eu-west-1'. Is account [...] bootstrapped?
[25%] start: Publishing 0d89df84ea307d9cb0d70fbd76481e4e86f449d075a2a082cc2d323ee69a98e4:[...]-eu-west-1
[50%] fail: No bucket named 'cdk-[...]-assets-[...]-eu-west-1'. Is account [...]bootstrapped?
[50%] start: Publishing 6c0316fef24d0df8a9a705c77052001217d864f49af386539d01df54618cd131:[...]-eu-west-1
[75%] fail: No bucket named 'cdk-[...]-assets-[...]-eu-west-1'. Is account [...] bootstrapped?
[75%] start: Publishing 043c5f22362938323bc0a119b816ec6c79edc16287aadad0fea43e032d122d0c:[...]-eu-west-1
[100%] fail: No bucket named 'cdk-[...]-eu-west-1'. Is account [...] bootstrapped?

 ❌  hpc-test-sst-debug-stack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at publishAssets (C:\Users\me\workspace\test-sst\node_modules\aws-cdk\lib\util\asset-publishing.ts:27:11)
    at CloudFormationDeployments.publishStackAssets (C:\Users\me\workspace\test-sst\node_modules\aws-cdk\lib\api\cloudformation-deployments.ts:418:7)
    at CloudFormationDeployments.deployStack (C:\Users\me\workspace\test-sst\node_modules\aws-cdk\lib\api\cloudformation-deployments.ts:299:5)
    at CdkToolkit.deploy (C:\Users\me\workspace\test-sst\node_modules\aws-cdk\lib\cdk-toolkit.ts:208:24)
    at initCommandLine (C:\Users\me\workspace\test-sst\node_modules\aws-cdk\lib\cli.ts:310:12)

Failed to publish one or more assets. See the error messages above for more information.

 ❌  hpc-test-sst-debug-stack failed: The hpc-test-sst-debug-stack stack failed to deploy.


Stack hpc-test-sst-debug-stack
  Status: failed
  Error: The hpc-test-sst-debug-stack stack failed to deploy.

Failed to deploy the debug stack
```

I'm quite new to AWS and serverless, but the above looks to me like it's trying to re-use old roles and buckets that don't exist any longer? Should it create new ones in that case?

**Comment by HundredPercentCoverage** [comment]
Turns out I had deleted everything except the Cloudformation stacks manually.
