### ISSUE TITLE
Live Lambda Dev errors with no `event.requestContext.time`

### ISSUE THREAD

**Issue by SpencerDuball** [serverless-stack/serverless-stack#1726]
## Issue
I am receiving an error where Lambda is not getting event data when invoking locally.

## Expected
I should be able to get event data from lambda when invoking locally.

## Error Message
```sh
==========================
 Starting Live Lambda Dev
==========================

SST Console: https://console.serverless-stack.com/spencerduball/spencer-duball/local
Debug session started. Listening for requests...
f5e1f37c-0e6a-4c9d-b46e-a84cd4ccf697 REQUEST spencer-duball-spencerduball--apiLambdaGET2D5CB7A7-hj72V2JVUFrb [functions/lambda.handler] invoked
f5e1f37c-0e6a-4c9d-b46e-a84cd4ccf697 ERROR TypeError: Cannot read properties of undefined (reading 'time') 
 TypeError: Cannot read properties of undefined (reading 'time')
    at Runtime.handler (file:///Users/sduball/LocalStorage/websites/spencerduball.com/.sst/artifacts/spencer-duball-spencerduball-MyStack-api-Lambda_GET_-/backend/functions/lambda.js:8:78)
    at Runtime.handleOnce (file:///Users/sduball/LocalStorage/websites/spencerduball.com/node_modules/@serverless-stack/aws-lambda-ric/lib/Runtime/Runtime.js:53:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Config
I have started with a blank SST project, I was just going through the docs to check it out was running the sample lambda when creating a Typescript app. Here is the`package.json` project config for reference:
```json
{
  "name": "spencerduball.com",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "sst start",
    "build": "sst build",
    "deploy": "sst deploy",
    "remove": "sst remove",
    "console": "sst console",
    "typecheck": "tsc --noEmit",
    "test": "vitest run"
  },
  "devDependencies": {
    "@serverless-stack/cli": "^1.2.1",
    "@serverless-stack/resources": "^1.2.1",
    "@tsconfig/node16": "^1.0.2",
    "typescript": "^4.6.4",
    "vitest": "^0.12.9"
  },
  "workspaces": [
    "backend",
    "web"
  ],
  "dependencies": {
    "ws": "7.4.0"
  }
}
```
## Lambda
Here is the lambda, and a snapshot in the console of the issue showing the "Request" has no attributes attached to the event.
```ts
import { APIGatewayProxyHandlerV2 } from "aws-lambda";

export const handler: APIGatewayProxyHandlerV2 = async (event) => {
  return {
    statusCode: 200,
    headers: { "Content-Type": "text/plain" },
    body: `Hello, World! Your request was received at ${event.requestContext.time}.`,
  };
};
```
![Screen Shot 2022-05-24 at 8 02 06 AM](https://user-images.githubusercontent.com/22606045/170041698-284c20f5-9b7c-40e2-9966-e18828ab2557.png)

**Comment by SpencerDuball** [comment]
Please note that I have added `ws@^7.4.0` to the project. This is because of another issue reported here: #1725

**Comment by adumeye** [comment]
Thank you for your response

**Comment by mutewinter** [comment]
Ran into this same issue and was thankful for this thread.
