### ISSUE TITLE
__dirname is not defined in ES module scope

### ISSUE THREAD

**Issue by stefanullinger** [serverless-stack/serverless-stack#1736]
Hello,

I was following the tutorial for creating a nextjs app.
https://serverless-stack.com/examples/how-to-create-a-nextjs-app-with-serverless.html

I was trying to deploy it to eu-central-1, but when I run `sst start`, I've get the following error:

`ReferenceError: __dirname is not defined in ES module scope
    at Module.getOrCreateBucket (file:///home/stefan/projects/2022/2022-05-foresight/foresight/node_modules/@serverless-stack/resources/dist/nextjs-site/cross-region-helper.js:17:47)
    at NextjsSite.createEdgeFunctionInNonUE1 (file:///home/stefan/projects/2022/2022-05-foresight/foresight/node_modules/@serverless-stack/resources/dist/NextjsSite.js:283:44)
    at NextjsSite.createEdgeFunction (file:///home/stefan/projects/2022/2022-05-foresight/foresight/node_modules/@serverless-stack/resources/dist/NextjsSite.js:250:20)
    at new NextjsSite (file:///home/stefan/projects/2022/2022-05-foresight/foresight/node_modules/@serverless-stack/resources/dist/NextjsSite.js:107:41)
    at EmptyStack.MyStack (file:///home/stefan/projects/2022/2022-05-foresight/foresight/.build/lib/index.js:15:16)
    at stack (file:///home/stefan/projects/2022/2022-05-foresight/foresight/node_modules/@serverless-stack/resources/dist/FunctionalStack.js:15:35)
    at App.stack (file:///home/stefan/projects/2022/2022-05-foresight/foresight/node_modules/@serverless-stack/resources/dist/App.js:282:16)
    at Module.default (file:///home/stefan/projects/2022/2022-05-foresight/foresight/.build/lib/index.js:38:7)
    at file:///home/stefan/projects/2022/2022-05-foresight/foresight/.build/run.mjs:92:16`

I am using node v16.14.2.
Is there something I have to change in the configuration to make it work?

Thanks in advance for any help!

**Comment by stefanullinger** [comment]
So when deploying to another region it is using the cross-region-helper.
https://github.com/serverless-stack/serverless-stack/blob/master/packages/resources/src/nextjs-site/cross-region-helper.ts#L20

And it seems it is using ES modules, so __dirname is not available.
Could this post https://flaviocopes.com/fix-dirname-not-defined-es-module-scope/ help to fix the code in the cross-region-helper?

**Comment by subssn21** [comment]
This should be fixed as of release 1.2.7
