### ISSUE TITLE
 Error: There is already a Construct with name 'PostConfirmationCognito' in Function [postConfirmation]

### ISSUE THREAD

**Issue by ThomasP1988** [serverless-stack/serverless-stack#413]
Hi everyone,

i have a cognito class where i am building two user/identity pool (admin/customer).

On both of them i want to use a lambda function as a trigger:

So i create a sttFunction in the constructor and i pass this function to my lambda triggers

`
  public postConfirmation: sst.Function;
  public preSignUp: sst.Function;
  public customMessage: sst.Function;

  constructor(scope: sst.App, id: string, props?: sst.StackProps) {
    super(scope, id, props);
    this.stage = scope.stage;

    this.postConfirmation = new sst.Function(this, "postConfirmation", {
      handler: "./event/cognito.postConfirmation",
    });

    this.preSignUp = new sst.Function(this, "preSignup", {
      handler: "./event/cognito.preSignup"
    });

    this.customMessage = new sst.Function(this, "customMessage", {
      handler: "./event/cognito.customMessage"
    });
  }`
  
  `  lambdaTriggers: {
        postConfirmation: this.postConfirmation,
        preSignUp: this.preSignUp,
        customMessage: this.customMessage
      }`

then i get this error when trying to deploy 
`Error: There is already a Construct with name 'PostConfirmationCognito' in Function [postConfirmation]
    at Node.addChild (/resources/node_modules/constructs/src/construct.ts:534:13)
    at new Node (/resources/node_modules/constructs/src/construct.ts:75:22)
    at new ConstructNode (/resources/node_modules/@aws-cdk/core/lib/construct-compat.ts:291:24)
    at Object.createNode (/resources/node_modules/@aws-cdk/core/lib/construct-compat.ts:78:11)
    at new Construct (/resources/node_modules/constructs/src/construct.ts:575:26)
    at new Construct (/resources/node_modules/@aws-cdk/core/lib/construct-compat.ts:75:5)
    at new CfnElement (/resources/node_modules/@aws-cdk/core/lib/cfn-element.ts:57:5)
    at new CfnRefElement (/resources/node_modules/@aws-cdk/core/lib/cfn-element.ts:148:1)
    at new CfnResource (/resources/node_modules/@aws-cdk/core/lib/cfn-resource.ts:83:5)
    at new CfnPermission (/resources/node_modules/@aws-cdk/aws-lambda/lib/lambda.generated.ts:3442:9)`
    
    Am I doing something wrong or is it a limitation?
    Thanks for your help

**Comment by fwang** [comment]
Hi @ThomasP1988, yeah for any construct in CDK, `id` needs to be unique within the same `scope`.
