### ISSUE TITLE
typescript cannot be found for type check on windows

### ISSUE THREAD

**Issue by RyanHow** [serverless-stack/serverless-stack#65]
Windows 10
```
npx create-serverless-stack@latest myapp --language typescript
cd myapp
npx sst build
```

following error

```
Running type checker
Error: There was a problem finding typescript
    at getBinPath (C:\working\myapp\node_modules\@serverless-stack\cli\scripts\util\cdkHelpers.js:45:11)
    at typeCheck (C:\working\myapp\node_modules\@serverless-stack\cli\scripts\util\cdkHelpers.js:210:9)
    at runChecks (C:\working\myapp\node_modules\@serverless-stack\cli\scripts\util\cdkHelpers.js:236:48)
    at prepareCdk (C:\working\myapp\node_modules\@serverless-stack\cli\scripts\util\cdkHelpers.js:362:9)
There was a problem type checking the source.
```

I changed `@serverless-stack\cli\scripts\util\cdkHelpers.js:40` from `filePath.match(/(^.*\/node_modules)\/.*$/);` to `filePath.match(/(^.*[\/\\]node_modules)[\/\\].*$/);` and it works 

After this fixed then I get another issue

```
Type checking Lambda function source

TypeError: Cannot read property 'toString' of undefined
    at App.typeCheck (C:\working\myapp\node_modules\@serverless-stack\resources\src\App.ts:263:28)
    at C:\working\myapp\node_modules\@serverless-stack\resources\src\App.ts:193:12
    at Array.forEach (<anonymous>)
    at App.processInputFiles (C:\working\myapp\node_modules\@serverless-stack\resources\src\App.ts:190:38)
    at App.synth (C:\working\myapp\node_modules\@serverless-stack\resources\src\App.ts:159:12)
    at process.<anonymous> (C:\working\myapp\node_modules\@aws-cdk\core\lib\app.ts:123:45)
    at Object.onceWrapper (events.js:421:26)
    at process.emit (events.js:314:20)
    at process.emit (C:\working\myapp\node_modules\source-map-support\source-map-support.js:495:21)

There was an error synthesizing your app.
```

**Comment by jayair** [comment]
Thanks for taking a crack at fixing it. I'll take a look at this for the next release.
