### ISSUE TITLE
Linting source - Error: spawnSync node ENAMETOOLONG

### ISSUE THREAD

**Issue by RyanHow** [serverless-stack/serverless-stack#66]
Windows 10

I have a fairly simple cdk file that creates a load balancer and containter.

I get the follow error...

Note: If I hack the source and remove .js file type checking then it works fine

```
npx sst build
```

```
Preparing your SST app
Detected tsconfig.json
Transpiling source
Linting source
Error: spawnSync node ENAMETOOLONG
    at Object.spawnSync (internal/child_process.js:1070:20)
    at Object.spawnSync (child_process.js:602:24)
    at Function.spawnSync [as sync] (C:\working\myapp\node_modules\cross-spawn\index.js:26:23)
    at lint (C:\working\myapp\node_modules\@serverless-stack\cli\scripts\util\cdkHelpers.js:176:26)
    at runChecks (C:\working\myapp\node_modules\@serverless-stack\cli\scripts\util\cdkHelpers.js:237:30)
    at prepareCdk (C:\working\myapp\node_modules\@serverless-stack\cli\scripts\util\cdkHelpers.js:363:9) {
  errno: -4064,
  code: 'ENAMETOOLONG',
  syscall: 'spawnSync node',
  path: 'node',
  spawnargs: [
    'C:\\working\\myapp\\.build\\eslint.js',
    '--color',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-elasticloadbalancingv2\\lib\\elasticloadbalancingv2.generated.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\region-info\\lib\\default.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\region-info\\lib\\fact.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\region-info\\lib\\region-info.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\region-info\\lib\\built-ins.generated.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\region-info\\lib\\index.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\util.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\principals.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\policy-statement.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\policy-document.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\iam.generated.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\managed-policy.js',
    'C:\\working\\myapp\\node_modules\\constructs\\lib\\aspect.js',
    'C:\\working\\myapp\\node_modules\\constructs\\lib\\metadata.js',
    'C:\\working\\myapp\\node_modules\\constructs\\lib\\private\\dependency.js',
    'C:\\working\\myapp\\node_modules\\constructs\\lib\\private\\stack-trace.js',
    'C:\\working\\myapp\\node_modules\\constructs\\lib\\private\\uniqueid.js',
    'C:\\working\\myapp\\node_modules\\constructs\\lib\\construct.js',
    'C:\\working\\myapp\\node_modules\\constructs\\lib\\index.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\grant.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\policy.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\private\\immutable-role.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\role.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\user.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\group.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\lazy-role.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\identity-base.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\unknown-principal.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\oidc-provider.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-iam\\lib\\index.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-ec2\\lib\\peer.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-ec2\\lib\\connections.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-ec2\\lib\\ec2.generated.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\cloud-assembly\\schema.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\cloud-assembly\\metadata-schema.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\cloud-assembly\\artifact-schema.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\cloud-assembly\\context-queries.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\cloud-assembly\\index.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\assets\\schema.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\assets\\docker-image-asset.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\assets\\file-asset.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\assets\\aws-destination.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\assets\\index.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\jsonschema\\lib\\helpers.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\jsonschema\\lib\\attribute.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\jsonschema\\lib\\scan.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\jsonschema\\lib\\validator.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\jsonschema\\lib\\index.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\internal\\constants.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\internal\\debug.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\internal\\re.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\internal\\identifiers.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\classes\\semver.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\parse.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\valid.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\clean.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\inc.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\compare.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\eq.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\diff.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\major.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\minor.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\patch.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\prerelease.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\rcompare.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\compare-loose.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\compare-build.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\sort.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\rsort.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\gt.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\lt.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\neq.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\gte.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\lte.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\cmp.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\coerce.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\classes\\range.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\classes\\comparator.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\functions\\satisfies.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\ranges\\to-comparators.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\ranges\\max-satisfying.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\ranges\\min-satisfying.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\ranges\\min-version.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\ranges\\valid.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\ranges\\outside.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\ranges\\gtr.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\ranges\\ltr.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\ranges\\intersects.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\ranges\\simplify.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\ranges\\subset.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\node_modules\\semver\\index.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\manifest.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cloud-assembly-schema\\lib\\index.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\aws-ec2\\lib\\security-group.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cx-api\\lib\\cxapi.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cx-api\\lib\\context\\vpc.js',
    'C:\\working\\myapp\\node_modules\\@aws-cdk\\cx-api\\lib\\context\\ami.js',
    ... 609 more items
  ]
}
There was a problem linting the source.
```

**Comment by RyanHow** [comment]
Same setup as last issue https://github.com/serverless-stack/serverless-stack/issues/66 , but I have a bit more CDK code in there

**Comment by jayair** [comment]
Thanks for the details. It should ignore all the files inside the node_modules by default. I'll fix it in the next release.

**Comment by jayair** [comment]
Give the new release a try and let me know if it works.

https://github.com/serverless-stack/serverless-stack/releases/tag/v0.7.0

**Comment by RyanHow** [comment]
@jayair brilliant!. Works perfectly.
